rollback #28

diff --git a/CA6/Part1/Jenkinsfile b/CA6/Part1/Jenkinsfile
--- a/CA6/Part1/Jenkinsfile
+++ b/CA6/Part1/Jenkinsfile
@@ -98,11 +98,30 @@ pipeline {
                                 env.BLUE = "200"
                             } else {
                                 echo "Error on Blue VM. Status: ${result}"
-                                exit 1
                             }
                         } else {
                             bat(script: "curl -s -o -w $url", returnStdout: true)
                             echo 'Web application up and running!'
+                        }
+                    }
+                }
+        }
+
+        stage('Rollback') {
+                steps {
+                    script {
+                        if (env.BLUE != "200") {
+                            //sh "vagrant halt green"
+                            sh "vagrant up green --provision"
+                        }
+
+                        result = sh(script: 'curl -m 5 -s -o /dev/null -w \"%{http_code}\" http://localhost:8091/employees', returnStdout: true)
+                        if (result == '200' || result == '302') {
+                            echo 'Web application up and running on Green VM!'
+                            env.BLUE = "200"
+                        } else {
+                            echo "Error on Green VM. Status: ${result}"
+                            exit 1
                         }
                     }
                 }
@@ -129,7 +148,7 @@ pipeline {
 
        failure {
             echo "Build failed!"
-            script {
+            /*script {
                 if (env.BLUE != "200") {
                     //sh "vagrant halt green"
                     sh "vagrant up green --provision"
@@ -143,7 +162,7 @@ pipeline {
                     echo "Error on Green VM. Status: ${result}"
                     exit 1
                 }
-            }
+            }*/
        }
     }
 }
