rollback #28

diff --git a/CA6/Part1/Jenkinsfile b/CA6/Part1/Jenkinsfile
--- a/CA6/Part1/Jenkinsfile
+++ b/CA6/Part1/Jenkinsfile
@@ -108,26 +108,6 @@ pipeline {
                 }
         }
 
-        /*stage('Rollback') {
-                steps {
-                    script {
-                        if (env.BLUE != "200") {
-                            //sh 'vagrant halt green'
-                            sh 'vagrant up green --provision'
-                        }
-
-                        result = sh(script: 'curl -m 5 -s -o /dev/null -w \"%{http_code}\" http://localhost:8091/employees', returnStdout: true)
-                        if (result == '200' || result == '302') {
-                            echo 'Web application up and running on Green VM!'
-                            env.BLUE = "200"
-                        } else {
-                            echo "Error on Green VM. Status: ${result}"
-                            exit 1
-                        }
-                    }
-                }
-        }*/
-
      }
 
     post {
@@ -149,20 +129,27 @@ pipeline {
 
        failure {
             echo "Build failed!"
+
             dir('CA6/Part1') {
                 script {
                     if (env.BLUE != "200") {
-                        //sh "vagrant halt green"
-                        sh "vagrant up green --provision"
-                    }
+                        echo "Starting Rollback..."
 
-                    result = sh(script: 'curl -m 5 -s -o /dev/null -w \"%{http_code}\" http://localhost:8091/employees', returnStdout: true)
-                    if (result == '200' || result == '302') {
-                        echo 'Web application up and running on Green VM!'
-                        env.BLUE = "200"
-                    } else {
-                        echo "Error on Green VM. Status: ${result}"
-                        exit 1
+                        echo "Stopping Green VM..."
+                        sh "vagrant halt green"
+
+                        echo "Starting Green VM with last stable version..."
+                        sh "vagrant up green --provision"
+
+                        echo "Starting Green HealthCheck..."
+                        result = sh(script: 'curl -m 5 -s -o /dev/null -w \"%{http_code}\" http://localhost:8091/employees', returnStdout: true)
+                        if (result == '200' || result == '302') {
+                            echo 'Web application up and running on Green VM!'
+                            env.BLUE = "200"
+                        } else {
+                            echo "Error on Green VM. Status: ${result}"
+                            exit 1
+                        }
                     }
                 }
             }
